// Career roadmaps for 5 domains
const roadmaps = {
    'B.Tech / AI-ML Engineering': {
        key: 'technology',
        title: 'B.Tech / AI-ML Engineering',
        icon: '🤖',
        color: '#6366f1',
        tagline: 'Build the future with intelligence',
        requiredSubjects: ['Mathematics', 'Physics', 'Computer Science', 'Statistics', 'Data Structures'],
        entranceExams: ['JEE Main', 'JEE Advanced', 'BITSAT', 'VITEEE', 'SRMJEEE'],
        degreeDuration: '4 Years (B.Tech) + 2 Years optional (M.Tech/MS)',
        topColleges: ['IIT Bombay', 'IIT Delhi', 'NIT Warangal', 'BITS Pilani', 'IIIT Hyderabad'],
        salaryRange: '₹8–50 LPA (fresher to senior)',
        careerGrowth: 'AI Engineer → Senior AI Engineer → ML Lead → Principal Scientist → CTO',
        milestones: [
            { year: 'Now', title: 'Foundation', desc: 'Focus on Maths, Physics, and coding basics (Python/C++)' },
            { year: 'Year 1', title: 'JEE Preparation', desc: 'Clear JEE Main/Advanced with strong Maths score' },
            { year: 'Year 2-3', title: 'B.Tech Core', desc: 'DSA, Algorithms, Machine Learning fundamentals' },
            { year: 'Year 3-4', title: 'Specialization', desc: 'Deep Learning, NLP, Computer Vision, Research projects' },
            { year: 'Year 4', title: 'Internships & Placements', desc: 'Google, Amazon, Microsoft, TCS, Infosys target companies' },
            { year: 'Post Grad', title: 'Career Growth', desc: 'Join AI startups, FAANG companies, or do MS abroad' },
        ],
    },
    'MBBS / Healthcare': {
        key: 'medical',
        title: 'MBBS / Healthcare',
        icon: '🏥',
        color: '#10b981',
        tagline: 'Heal lives, change the world',
        requiredSubjects: ['Biology', 'Chemistry', 'Physics', 'Botany', 'Zoology'],
        entranceExams: ['NEET-UG', 'JIPMER', 'AIIMS (via NEET)'],
        degreeDuration: '5.5 Years (MBBS) + 3 Years (MD/MS) optional',
        topColleges: ['AIIMS Delhi', 'JIPMER Puducherry', 'CMC Vellore', 'KMC Manipal', 'Osmania Medical College'],
        salaryRange: '₹5–30 LPA (junior doctor to specialist)',
        careerGrowth: 'Intern → Junior Doctor → Resident → Specialist → HOD / Senior Consultant',
        milestones: [
            { year: 'Now', title: 'Foundation', desc: 'Master Biology, Chemistry — NCERT thoroughly' },
            { year: 'Year 1', title: 'NEET Preparation', desc: 'NEET-UG coaching, practice 120+ questions daily' },
            { year: 'Year 1-5', title: 'MBBS Program', desc: 'Pre-clinical (Anatomy, Physiology) + Clinical rotations' },
            { year: 'Year 5-6', title: 'Internship', desc: 'Mandatory 1-year rotating internship across departments' },
            { year: 'Year 7+', title: 'PG Entrance', desc: 'NEET-PG for MD/MS specialization' },
            { year: 'Year 10+', title: 'Specialist', desc: 'Cardiology, Neurology, Surgery specialization' },
        ],
    },
    'Law / Public Policy': {
        key: 'law',
        title: 'Law / Public Policy',
        icon: '⚖️',
        color: '#f59e0b',
        tagline: 'Champion justice and governance',
        requiredSubjects: ['Political Science', 'History', 'English', 'Economics', 'Civics'],
        entranceExams: ['CLAT', 'AILET', 'LSAT India', 'MH CET Law'],
        degreeDuration: '5 Years (BA LLB integrated) or 3 Years (LLB after graduation)',
        topColleges: ['NLSIU Bangalore', 'NLU Delhi', 'NALSAR Hyderabad', 'NLU Mumbai', 'Symbiosis Law School'],
        salaryRange: '₹4–40 LPA (from associate to senior partner)',
        careerGrowth: 'Law Intern → Associate Lawyer → Senior Associate → Partner → Judge / Arbitrator',
        milestones: [
            { year: 'Now', title: 'Foundation', desc: 'Strong reading, comprehension and current affairs habits' },
            { year: 'Year 1', title: 'CLAT Preparation', desc: 'Legal reasoning, GK, English, Maths (CLAT syllabus)' },
            { year: 'Year 1-5', title: 'BA LLB Program', desc: 'Constitutional law, IPC, CPC, Contract law, Torts' },
            { year: 'Year 3-4', title: 'Moot Courts', desc: 'Participate in national and international moot courts' },
            { year: 'Year 5', title: 'Internships', desc: 'Intern at courts, law firms (AZB, Cyril Amarchand etc.)' },
            { year: 'Post Grad', title: 'Specialization', desc: 'Corporate law, Criminal law, IP law, Human Rights' },
        ],
    },
    'Business / BBA-MBA': {
        key: 'business',
        title: 'Business / BBA-MBA',
        icon: '💼',
        color: '#8b5cf6',
        tagline: 'Lead markets, build empires',
        requiredSubjects: ['Economics', 'Mathematics', 'Accountancy', 'Business Studies', 'Statistics'],
        entranceExams: ['CAT', 'XAT', 'SNAP', 'IPU CET', 'NMIMS CET (for BBA)'],
        degreeDuration: '3 Years (BBA) + 2 Years (MBA)',
        topColleges: ['IIM Ahmedabad', 'IIM Bangalore', 'IIM Calcutta', 'XLRI Jamshedpur', 'SP Jain Mumbai'],
        salaryRange: '₹6–80 LPA (fresher to senior management)',
        careerGrowth: 'Management Trainee → Business Analyst → Manager → General Manager → CEO / Entrepreneur',
        milestones: [
            { year: 'Now', title: 'Foundation', desc: 'Build financial literacy, read business news (ET, Mint)' },
            { year: 'Year 1', title: 'BBA Entrance', desc: 'Prepare for IPU CET, NMIMS — aptitude + GK' },
            { year: 'Year 1-3', title: 'BBA Program', desc: 'Marketing, Finance, Operations, HR fundamentals' },
            { year: 'Year 2-3', title: 'Internships', desc: 'Intern at startups, MNCs (consult, finance, marketing)' },
            { year: 'Year 4-5', title: 'CAT + MBA', desc: 'Target CAT 99%ile for IIMs, XAT for XLRI' },
            { year: 'Post MBA', title: 'Leadership', desc: 'Consulting (McKinsey, BCG), Banking, or Start your own venture' },
        ],
    },
    'Multimedia & Design': {
        key: 'design',
        title: 'Multimedia & Design',
        icon: '🎨',
        color: '#ec4899',
        tagline: 'Create, inspire, and shape culture',
        requiredSubjects: ['Fine Arts', 'Computer Applications', 'English', 'Photography', 'Design Basics'],
        entranceExams: ['NID DAT', 'UCEED', 'CEED', 'NIFT Entrance', 'MIT ID Entrance'],
        degreeDuration: '4 Years (B.Des) + 2 Years optional (M.Des)',
        topColleges: ['NID Ahmedabad', 'IDC IIT Bombay', 'NIFT Delhi', 'MIT Institute of Design', 'Srishti Institute'],
        salaryRange: '₹4–25 LPA (junior designer to creative director)',
        careerGrowth: 'Junior Designer → UI/UX Designer → Senior Designer → Art Director → Creative Director',
        milestones: [
            { year: 'Now', title: 'Foundation', desc: 'Build a portfolio: sketches, digital art, UI mockups' },
            { year: 'Year 1', title: 'Entrance Prep', desc: 'NID DAT / UCEED — design aptitude, sketching, GK' },
            { year: 'Year 1-4', title: 'B.Des Program', desc: 'Typography, UX Research, Motion Graphics, Branding' },
            { year: 'Year 2-3', title: 'Build Portfolio', desc: 'Freelance projects, Behance profile, Dribbble presence' },
            { year: 'Year 4', title: 'Industry Work', desc: 'Intern at agencies, product companies, or film industries' },
            { year: 'Post Grad', title: 'Creative Lead', desc: 'UX architect, Brand strategist, or start creative agency' },
        ],
    },
};

module.exports = roadmaps;
